theme: jekyll-theme-minimal
layout: splash

title: [BIOMAP]
description: [Biomagnification factor Prediction project]
show_downloads: false
plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-avatar

picture:
  source: "images/logo.png"
  markup: "picture"
